<?php
/*
 * Builds the structured data (JSON-LD) that search engines and AI assistants read, from what the
 * pages already say, so the two can never disagree:
 *   - dist/index.html: the bakery (name, area, contact, payment, box prices) and the website
 *   - dist/faq.html:   every question and answer shown on the FAQ page
 * Only facts that are visible on the site are used — no opening hours, address, reviews or ratings.
 *
 * Run after changing the FAQ, the box prices or the business details:
 *     php server/tools/structured-data.php
 * The self-test (server/tests/run.php) fails if a page and its structured data are out of step.
 */
declare(strict_types=1);

require_once dirname(__DIR__) . '/lib/settings.php';

const SD_START = '<!-- structured-data: generated by server/tools/structured-data.php from this page; edit the page, then run the tool -->';
const SD_END = '<!-- /structured-data -->';

/** The website address, taken from the sitemap (the same source set-domain.php uses). */
function sd_site_url(string $dist): string
{
    if (!preg_match('#<loc>(https://[^/<]+)/#', (string) file_get_contents("$dist/sitemap.xml"), $m)) {
        throw new RuntimeException('Could not find the website address in sitemap.xml');
    }
    return $m[1];
}

function sd_text(DOMNode $node): string
{
    return trim(preg_replace('/\s+/u', ' ', $node->textContent) ?? '');
}

function sd_dom(string $html): DOMXPath
{
    $doc = new DOMDocument();
    libxml_use_internal_errors(true);
    $doc->loadHTML('<?xml encoding="utf-8"?>' . $html);
    libxml_clear_errors();
    return new DOMXPath($doc);
}

/** Every question on a page: [[question, answer], …] from its <details><summary>… blocks inside <main>. */
function sd_faq_items(string $html): array
{
    $x = sd_dom($html);
    $items = [];
    foreach ($x->query('//main//details') as $details) {
        $summary = $x->query('./summary', $details)->item(0);
        $answer = [];
        foreach ($x->query('./*[not(self::summary)]', $details) as $part) {
            $answer[] = sd_text($part);
        }
        if ($summary && $answer) {
            $items[] = [sd_text($summary), implode(' ', $answer)];
        }
    }
    return $items;
}

function sd_meta_description(string $html): string
{
    $node = sd_dom($html)->query('//meta[@name="description"]')->item(0);
    return $node instanceof DOMElement ? $node->getAttribute('content') : '';
}

function sd_json(array $data): string
{
    return json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_HEX_TAG | JSON_THROW_ON_ERROR);
}

function sd_faq_json(string $faqHtml, string $base): string
{
    return sd_json([
        '@context' => 'https://schema.org',
        '@type' => 'FAQPage',
        '@id' => "$base/faq.html#faq",
        'url' => "$base/faq.html",
        'mainEntity' => array_map(fn(array $qa) => [
            '@type' => 'Question',
            'name' => $qa[0],
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => $qa[1]],
        ], sd_faq_items($faqHtml)),
    ]);
}

/** $prices: box size => price in cents. */
function sd_business_json(string $indexHtml, string $base, array $prices): string
{
    $names = [4 => 'Box of 4 cookies', 6 => 'Half dozen (6 cookies)', 12 => 'Dozen (12 cookies)', 24 => 'Two dozen (24 cookies)', 36 => 'Three dozen (36 cookies)'];
    $dollars = fn(int $cents) => number_format($cents / 100, 2, '.', '');
    $offers = [];
    foreach ($prices as $size => $cents) {
        $offers[] = [
            '@type' => 'Offer',
            'name' => ($names[$size] ?? "Box of {$size} cookies") . ', mix and match flavors',
            'price' => $dollars($cents),
            'priceCurrency' => 'USD',
            'url' => "$base/order.html?box={$size}",
        ];
    }
    return sd_json([
        '@context' => 'https://schema.org',
        '@graph' => [
            [
                '@type' => 'WebSite',
                '@id' => "$base/#website",
                'url' => "$base/",
                'name' => 'Pashabakess',
                'inLanguage' => 'en-US',
                'publisher' => ['@id' => "$base/#bakery"],
            ],
            [
                '@type' => 'Bakery',
                '@id' => "$base/#bakery",
                'name' => 'Pashabakess',
                'description' => sd_meta_description($indexHtml),
                'url' => "$base/",
                'logo' => "$base/logo-192.jpg",
                'image' => ["$base/og-image.jpg", "$base/images/hero-1268.jpg"],
                'email' => 'pashabakess@gmail.com',
                'sameAs' => ['https://www.instagram.com/pashabakess/'],
                'address' => ['@type' => 'PostalAddress', 'addressLocality' => 'Tyngsboro', 'addressRegion' => 'MA', 'addressCountry' => 'US'],
                'areaServed' => ['@type' => 'City', 'name' => 'Tyngsboro, Massachusetts'],
                'servesCuisine' => 'Cookies',
                'priceRange' => '$' . number_format(min($prices) / 100) . '–$' . number_format(max($prices) / 100),
                'currenciesAccepted' => 'USD',
                'paymentAccepted' => 'Venmo, Cash App',
                'hasMenu' => "$base/menu.html",
                'hasOfferCatalog' => [
                    '@type' => 'OfferCatalog',
                    'name' => 'Mix-and-match cookie boxes, pickup only in Tyngsboro, MA, with one week’s notice',
                    'itemListElement' => $offers,
                ],
            ],
        ],
    ]);
}

/** Puts the JSON-LD block just before </head>, replacing an earlier generated block. */
function sd_replace_block(string $html, string $json): string
{
    $block = '  ' . SD_START . "\n  <script type=\"application/ld+json\">\n" . $json . "\n  </script>\n  " . SD_END . "\n";
    $html = preg_replace('#  ' . preg_quote(SD_START, '#') . '.*?' . preg_quote(SD_END, '#') . '\r?\n#s', '', $html) ?? $html;
    // Plain string insert: the JSON contains "$14" etc., which a regex replacement would treat as back-references.
    $at = strpos($html, '</head>');
    return $at === false ? $html : substr_replace($html, $block, $at, 0);
}

/** The pages as they should be: [path => html]. $prices: box size => cents. */
function sd_build(string $dist, array $prices): array
{
    $base = sd_site_url($dist);
    $index = (string) file_get_contents("$dist/index.html");
    $faq = (string) file_get_contents("$dist/faq.html");
    return [
        "$dist/index.html" => sd_replace_block($index, sd_business_json($index, $base, $prices)),
        "$dist/faq.html" => sd_replace_block($faq, sd_faq_json($faq, $base)),
    ];
}

/** Box prices as sold (the defaults in server/lib/settings.php — the same numbers the pages show). */
function sd_default_prices(): array
{
    $raw = json_decode(default_settings()['prices'], true);
    $prices = [];
    foreach (PB_BOX_SIZES as $size) {
        $prices[$size] = (int) $raw[(string) $size];
    }
    return $prices;
}

if (PHP_SAPI === 'cli' && realpath($_SERVER['argv'][0] ?? '') === realpath(__FILE__)) {
    $dist = dirname(__DIR__, 2) . '/dist';
    foreach (sd_build($dist, sd_default_prices()) as $file => $html) {
        $changed = $html !== file_get_contents($file);
        if ($changed) {
            file_put_contents($file, $html);
        }
        echo ($changed ? '  updated ' : '  unchanged ') . basename($file) . PHP_EOL;
    }
}
